// Turn non-printable characters into string representations.
// Example: '\n' = NL, or '\0' = NUL, etc.
pub fn stringify_npc(c: char) -> String {
    match c as u8 {
        0 => "NUL",   // Null
        1 => "SOH",   // Start of Heading
        2 => "STX",   // Start of Text
        3 => "ETX",   // End of Text
        4 => "EOT",   // End of Transmission
        5 => "ENQ",   // Enquiry
        6 => "ACK",   // Acknowledge
        7 => "BEL",   // Bell
        8 => "BS",    // Backspace
        9 => "HT",    // Horizontal Tab
        10 => "NL",   // NL Line Feed, New Line
        11 => "VT",   // Vertical Tab
        12 => "FF",   // NP Form Feed, New Page
        13 => "CR",   // Carriage Return
        14 => "SO",   // Shift Out
        15 => "SI",   // Shift In
        16 => "DLE",  // Data Link Escape
        17 => "DC1",  // Device Control 1
        18 => "DC2",  // Device Control 2
        19 => "DC3",  // Device Control 3
        20 => "DC4",  // Device Control 4
        21 => "NAK",  // Negative Acknowledge
        22 => "SYN",  // Synchronous Idle
        23 => "ETB",  // End of Transmission Block
        24 => "CAN",  // Cancel
        25 => "EM",   // End of Medium
        26 => "SUB",  // Substitute
        27 => "ESC",  // Escape
        28 => "FS",   // File Separator
        29 => "GS",   // Group Separator
        30 => "RS",   // Record Separator
        31 => "US",   // Unit Separator
        32 => "SPC",  // Space
        33 => "!",    // Exclamation Mark
        34 => "\"",   // Double Quote
        35 => "#",    // Hash or Number
        36 => "$",    // Dollar Sign
        37 => "%",    // Percentage
        38 => "&",    // Ampersand
        39 => "'",    // Single Quote
        40 => "(",    // Left Parenthesis
        41 => ")",    // Right Parenthesis
        42 => "*",    // Asterisk
        43 => "+",    // Plus Sign
        44 => ",",    // Comma
        45 => "-",    // Minus Sign
        46 => ".",    // Period
        47 => "/",    // Slash
        48 => "0",    // Zero
        49 => "1",    // Number One
        50 => "2",    // Number Two
        51 => "3",    // Number Three
        52 => "4",    // Number Four
        53 => "5",    // Number Five
        54 => "6",    // Number Six
        55 => "7",    // Number Seven
        56 => "8",    // Number Eight
        57 => "9",    // Number Nine
        58 => ":",    // Colon
        59 => ";",    // Semicolon
        60 => "<",    // Less Than
        61 => "=",    // Equals Sign
        62 => ">",    // Greater Than
        63 => "?",    // Question Mark
        64 => "@",    // At Sign
        65 => "A",    // Upper Case Letter A
        66 => "B",    // Upper Case Letter B
        67 => "C",    // Upper Case Letter C
        68 => "D",    // Upper Case Letter D
        69 => "E",    // Upper Case Letter E
        70 => "F",    // Upper Case Letter F
        71 => "G",    // Upper Case Letter G
        72 => "H",    // Upper Case Letter H
        73 => "I",    // Upper Case Letter I
        74 => "J",    // Upper Case Letter J
        75 => "K",    // Upper Case Letter K
        76 => "L",    // Upper Case Letter L
        77 => "M",    // Upper Case Letter M
        78 => "N",    // Upper Case Letter N
        79 => "O",    // Upper Case Letter O
        80 => "P",    // Upper Case Letter P
        81 => "Q",    // Upper Case Letter Q
        82 => "R",    // Upper Case Letter R
        83 => "S",    // Upper Case Letter S
        84 => "T",    // Upper Case Letter T
        85 => "U",    // Upper Case Letter U
        86 => "V",    // Upper Case Letter V
        87 => "W",    // Upper Case Letter W
        88 => "X",    // Upper Case Letter X
        89 => "Y",    // Upper Case Letter Y
        90 => "Z",    // Upper Case Letter Z
        91 => "[",    // Left Square Bracket
        92 => "\\",   // Backslash
        93 => "]",    // Right Square Bracket
        94 => "^",    // Caret or Circumflex
        95 => "\\_",  // Underscore
        96 => "`",    // Grave Accent
        97 => "a",    // Lower Case Letter a
        98 => "b",    // Lower Case Letter b
        99 => "c",    // Lower Case Letter c
        100 => "d",   // Lower Case Letter d
        101 => "e",   // Lower Case Letter e
        102 => "f",   // Lower Case Letter f
        103 => "g",   // Lower Case Letter g
        104 => "h",   // Lower Case Letter h
        105 => "i",   // Lower Case Letter i
        106 => "j",   // Lower Case Letter j
        107 => "k",   // Lower Case Letter k
        108 => "l",   // Lower Case Letter l
        109 => "m",   // Lower Case Letter m
        110 => "n",   // Lower Case Letter n
        111 => "o",   // Lower Case Letter o
        112 => "p",   // Lower Case Letter p
        113 => "q",   // Lower Case Letter q
        114 => "r",   // Lower Case Letter r
        115 => "s",   // Lower Case Letter s
        116 => "t",   // Lower Case Letter t
        117 => "u",   // Lower Case Letter u
        118 => "v",   // Lower Case Letter v
        119 => "w",   // Lower Case Letter w
        120 => "x",   // Lower Case Letter x
        121 => "y",   // Lower Case Letter y
        122 => "z",   // Lower Case Letter z
        123 => "{",   // Left Curly Bracket
        124 => "|",   // Vertical Bar
        125 => "}",   // Right Curly Bracket
        126 => "~",   // Tilde
        127 => "DEL", // Delete
        128 => "Ç",   //	Latin Capital Letter C With Cedilla
        129 => "ü",   //	Latin Small Letter U With Diaeresis
        130 => "é",   //	Latin Small Letter E With Acute
        131 => "â",   //	Latin Small Letter A With Circumflex
        132 => "ä",   //	Latin Small Letter A With Diaeresis
        133 => "à",   //	Latin Small Letter A With Grave
        134 => "å",   //	Latin Small Letter A With Ring Above
        135 => "ç",   //	Latin Small Letter C With Cedilla
        136 => "ê",   //	Latin Small Letter E With Circumflex
        137 => "ë",   //	Latin Small Letter E With Diaeresis
        138 => "è",   //	Latin Small Letter E With Grave
        139 => "ï",   //	Latin Small Letter I With Diaeresis
        140 => "î",   //	Latin Small Letter I With Circumflex
        141 => "ì",   //	Latin Small Letter I With Grave
        142 => "Ä",   //	Latin Capital Letter A With Diaeresis
        143 => "Å",   //	Latin Capital Letter A With Ring Above
        144 => "É",   //	Latin Capital Letter E With Acute
        145 => "§",   //	Latin Small Letter Ae
        146 => "Æ",   //	Latin Capital Letter Ae
        147 => "ô",   //	Latin Small Letter O With Circumflex
        148 => "ö",   //	Latin Small Letter O With Diaeresis
        149 => "ò",   //	Latin Small Letter O With Grave
        150 => "û",   //	Latin Small Letter U With Circumflex
        151 => "ù",   //	Latin Small Letter U With Grave
        152 => "ÿ",   //	Latin Small Letter Y With Diaeresis
        153 => "Ö",   //	Latin Capital Letter O With Diaeresis
        154 => "Ü",   //	Latin Capital Letter U With Diaeresis
        155 => "¢",   //	Cent Sign
        156 => "£",   //	Pound Sign, Pound Sterling, Irish Punt, Lira Sign
        157 => "¥",   //	Yen Sign, Yuan Sign
        158 => "₧",   //	Peseta Sign
        159 => "ƒ",   //	Latin Small Letter F With Hook, Florin Currency Symbol, Function Symbol
        160 => "á",   //	Latin Small Letter A With Acute
        161 => "í",   //	Latin Small Letter I With Acute
        162 => "ó",   //	Latin Small Letter O With Acute
        163 => "ú",   //	Latin Small Letter U With Acute
        164 => "ñ",   //	Latin Small Letter N With Tilde, Small Letter Enye
        165 => "Ñ",   //	Latin Capital Letter N With Tilde, Capital Letter Enye
        166 => "ª",   //	Feminine Ordinal Indicator
        167 => "º",   //	Masculine Ordinal Indicator
        168 => "¿",   //	Inverted Question Mark, Turned Question Mark
        169 => "⌐",   //	Reversed Not Sign, Beginning Of Line
        170 => "¬",   //	Not Sign, Angled Dash
        171 => "½",   //	Vulgar Fraction One Half
        172 => "¼",   //	Vulgar Fraction One Quarter
        173 => "¡",   //	Inverted Exclamation Mark
        174 => "«",   //	Left-Pointing Double Angle Quotation Mark, Left Guillemet, Chevrons
        175 => "»",   //	Right-Pointing Double Angle Quotation Mark, Right Guillemet
        176 => "░",   //	Light Shade
        177 => "▒",   //	Medium Shade, Speckles Fill, Dotted Fill
        178 => "▓",   //	Dark Shade
        179 => "│",   //	Box Drawings Light Vertical
        180 => "┤",   //	Box Drawings Light Vertical And Left
        181 => "╡",   //	Box Drawings Vertical Single And Left Double
        182 => "╢",   //	Box Drawings Vertical Double And Left Single
        183 => "╖",   //	Box Drawings Down Double And Left Single
        184 => "╕",   //	Box Drawings Down Single And Left Double
        185 => "╣",   //	Box Drawings Double Vertical And Left
        186 => "║",   //	Box Drawings Double Vertical
        187 => "╗",   //	Box Drawings Double Down And Left
        188 => "╝",   //	Box Drawings Double Up And Left
        189 => "╜",   //	Box Drawings Up Double And Left Single
        190 => "╛",   //	Box Drawings Up Single And Left Double
        191 => "┐",   //	Box Drawings Light Down And Left
        192 => "└",   //	Box Drawings Light Up And Right
        193 => "┴",   //	Box Drawings Light Up And Horizontal
        194 => "├",   //	Box Drawings Light Down And Horizontal
        195 => "├",   //	Box Drawings Light Vertical And Right
        196 => "─",   //	Box Drawings Light Horizontal
        197 => "┼",   //	Box Drawings Light Vertical And Horizontal
        198 => "╞",   //	Box Drawings Vertical Single And Right Double
        199 => "╟",   //	Box Drawings Vertical Double And Right Single
        200 => "╚",   //	Box Drawings Double Up And Right
        201 => "╔",   //	Box Drawings Double Down And Right
        202 => "╩",   //	Box Drawings Double Up And Horizontal
        203 => "╦",   //	Box Drawings Double Down And Horizontal
        204 => "╠",   //	Box Drawings Double Vertical And Right
        205 => "═",   //	Box Drawings Double Horizontal
        206 => "╬",   //	Box Drawings Double Vertical And Horizontal
        207 => "╧",   //	Box Drawings Up Single And Horizontal Double
        208 => "╨",   //	Box Drawings Up Double And Horizontal Single
        209 => "╤",   //	Box Drawings Down Single And Horizontal Double
        210 => "╥",   //	Box Drawings Down Double And Horizontal Single
        211 => "╙",   //	Box Drawings Up Double And Right Single
        212 => "╘",   //	Box Drawings Up Single And Right Double
        213 => "╒",   //	Box Drawings Down Single And Right Double
        214 => "╓",   //	Box Drawings Down Double And Right Single
        215 => "╫",   //	Box Drawings Vertical Double And Horizontal Single
        216 => "╪",   //	Box Drawings Vertical Single And Horizontal Double
        217 => "┘",   //	Box Drawings Light Up And Left
        218 => "┌",   //	Box Drawings Light Down And Right
        219 => "█",   //	Full Block, Solid Block
        220 => "▄",   //	Lower Half Block
        221 => "▌",   //	Left Half Block
        222 => "▐",   //	Right Half Block
        223 => "▀",   //	Upper Half Block
        224 => "α",   //	Greek Small Letter Alpha
        225 => "ß",   //	Latin Small Letter Sharp S, Eszett
        226 => "Γ",   //	Greek Capital Letter Gamma
        227 => "π",   //	Greek Small Letter Pi
        228 => "Σ",   //	Greek Capital Letter Sigma
        229 => "σ",   //	Greek Small Letter Sigma
        230 => "µ",   //	Micro Sign
        231 => "τ",   //	Greek Capital Letter Tau
        232 => "Φ",   //	Greek Capital Letter Phi
        233 => "Θ",   //	Greek Capital Letter Theta
        234 => "Ω",   //	Greek Capital Letter Omega
        235 => "δ",   //	Greek Small Letter Delta
        236 => "∞",   //	Infinity
        237 => "φ",   //	Greek Small Letter Phi
        238 => "ε",   //	Greek Small Letter Epsilon
        239 => "∩",   //	Intersection
        240 => "≡",   //	Identical To
        241 => "±",   //	Plus-Minus Sign
        242 => "≥",   //	Greater-Than Or Equal To
        243 => "≤",   //	Less-Than Or Equal To
        244 => "⌠",   //	Top Half Integral
        245 => "⌡",   //	Bottom Half Integral
        246 => "÷",   //	Division Sign, Obelus
        247 => "≈",   //	Almost Equal To, Asymptotic To
        248 => "°",   //	Degree Sign
        249 => "∙",   //	Bullet Operator
        250 => "·",   //	Middle Dot, Interpunct
        251 => "√",   //	Square Root, Radical Sign
        252 => "ⁿ",   //	Superscript Latin Small Letter N
        253 => "²",   //	Superscript Two, Squared
        254 => "■",   //	Black Square
        255 => "NBS",
    }
    .to_string()
}
